# Generated by Django 4.2.2 on 2023-06-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateinfomodel',
            name='pril_kaz',
            field=models.ImageField(blank=True, upload_to='uploads/graduates/prilkaz/', verbose_name='Приложение КАЗ'),
        ),
        migrations.AddField(
            model_name='graduateinfomodel',
            name='pril_ru',
            field=models.ImageField(blank=True, upload_to='uploads/graduates/prilru/', verbose_name='Приложение РУ'),
        ),
    ]
