# Generated by Django 5.0.6 on 2024-05-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_socialpartnersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpartnersmodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя партнера'),
        ),
    ]
