# Generated by Django 5.0.6 on 2024-05-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_socialpartnersmodel_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialpartnersmodel',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
    ]
