# Generated by Django 5.0.6 on 2024-05-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_specmodel_sokr_spec_name_alter_specmodel_spec_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateinfomodel',
            name='foto',
            field=models.ImageField(blank=True, default='uploads/default.png', upload_to='uploads/graduates/foto/', verbose_name='Фото'),
        ),
    ]
